### ISSUE TITLE
French Guiana is linked to France & listed as France

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/caselaw#12]
Please fix.

**Comment by mzeinstra** [comment]
Wikipedia states that French Guiana is an overseas territory of France, the naming would technically be correct.

**Comment by khyati18** [comment]
Can I work on this issue ?

**Comment by kgodey** [comment]
I'm not sure if this is a still relevant issue given what @mzeinstra said, @peterspdx, could you please confirm what you'd expect the behavior to be?

**Comment by pavitra14** [comment]
If this issue is still relevant, I request to be assigned to it.

**Comment by kgodey** [comment]
@TimidRobot to determine next steps.

**Comment by mzeinstra** [comment]
I don't believe it is contested that French Guiana is part of France and that French law applies, including case law. See https://en.wikipedia.org/wiki/Overseas_France
