### ISSUE TITLE
Country vs. Jurisdiction

### ISSUE THREAD

**Issue by robmyers** [creativecommons/caselaw#3]
In the web site, the pages generated from the spreadsheets are organised according to Country.

The current CASES sheet has Jurisdiction, which is richer than Country, e.g. we have "US", "US (Texas)" and "US (DC)" for Jurisdictions in the United States.

To make the software smarter about this would make it less reliable, so I would prefer to use the list of countries that we used for the Rights Back Resource. This will help assemble the map and the pages (as well as search and drop-down menus). That list can be found here:

http://jvectormap.com/maps/world/world/

If this makes sense, we should add a "Country" column to the CASES and SCHOLARSHIP sheets and add the Country for existing entries. So if the Jurisdiction is "US (DC)" the Country is "United States".

Or if I am confusing matters we should discuss it here. :-)

**Comment by samanthalisae** [comment]
It makes sense to me. I added a column in the spreadsheet for both the CASES and SCHOLARSHIP labelled "Country". Do you think we should keep the jurisdictions @peterspdx ?

**Comment by peterspdx** [comment]
+ 1 @robmyers @samanthalisae please move ahead with Country.

**Comment by robmyers** [comment]
@samanthalisae Thank you!

@peterspdx Should we keep the jurisdictions?

**Comment by peterspdx** [comment]
Let's add country and leave jurisdiction, the richer choice. We may need to provide explanations below each to differentiate, so we get the information we need for jurisdiction. But the map should be tied to the "country" field.

Thanks @robmyers

**Comment by robmyers** [comment]
Done. Thank you!
