### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by robmyers** [creativecommons/caselaw#4]
The current (in progress!) state of the site still has the Rights Back Resource banner on the front page and its logo at the bottom of the page.

Do we want a new banner and a distinctive logo for the Case Law site, or do should I just remove the banner and change the footer to the CC logotype?

**Comment by peterspdx** [comment]
Please remove the banner etc. relative to rights back resource, and insert the standard CC banner etc. Will take care of getting something designed via @little-wow soon. Thanks!
