### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by samanthalisae** [creativecommons/caselaw#5]
Can you put this text in between the placeholder picture and the map on the landing page? 
		
Welcome to the Creative Commons Legal Database! This database comprises case law and legal scholarship to help you learn more about legal issues surrounding Creative Commons licenses and legal tools. These resources aim to help you clearly understand the enforceability and precedents set by courts around the world concerning Creative Commons licenses. The Case Law Database includes court decisions from around the globe concerning Creative Commons. The Scholarship Database aims to provide users with articles and resources concerning the use and enforceability of Creative Commons licenses.

**Comment by samanthalisae** [comment]
Updated text available in the google doc. https://docs.google.com/document/d/1toG-WxUBr4qvCiQiX8Fi00Tf2QQnHVo_KEM3OlKeezs/edit?usp=sharing

**Comment by robmyers** [comment]
Done! We can flesh out the content that is currently placeholders with other issues.

Thank you!
