### ISSUE TITLE
Increase the padding-bottom in Scholarship detail page

### ISSUE THREAD

**Issue by panchovm** [creativecommons/caselaw#52]
### Page: Scholarship detail
The padding-bottom of the first section, where breadcrumb and title are, looks tight.

<img width="712" alt="Screen Shot 2020-08-12 at 16 01 42" src="https://user-images.githubusercontent.com/895819/90062255-629eff80-dcb5-11ea-8276-ebeb61ac056a.png">

## Expectation
The padding-bottom space should be `64px`.

**Comment by Aakash2408** [comment]
Hey @kgodey , @krysal  is this issue resolved or I can take this?

**Comment by krysal** [comment]
@Aakash2408 This is already fixed in #70, just waiting for review.
