### ISSUE TITLE
Wrong alignment of content in Case form page

### ISSUE THREAD

**Issue by panchovm** [creativecommons/caselaw#55]
### Page: Case form
The content of the header, first, and section sections are not left-align.

<img width="287" alt="Screen Shot 2020-08-12 at 16 37 51" src="https://user-images.githubusercontent.com/895819/90065538-6f722200-dcba-11ea-8a56-13b996fc1e08.png">

## Expectation
All content should be left-align based on the grid.

**Comment by Aakash2408** [comment]
Hey, @kgodey Can I take this up?

**Comment by kgodey** [comment]
I'm not sure if @krysal is already working on this so I'll leave it up to her.

**Comment by krysal** [comment]
@panchovm What do you think about centering the form? The free space on the right side feels odd.

**Comment by panchovm** [comment]
I am fine with that 🙂
