### ISSUE TITLE
Create Individual Pages for Case Law and Scholarship

### ISSUE THREAD

**Issue by samanthalisae** [creativecommons/caselaw#7]
Please make individual pages for all cases and articles in the master spreadsheet that are highlighted in green. 

https://docs.google.com/spreadsheets/d/1LVc6FM3RwJqqcyF6i3J1YDMfhzNaxbUgZ3YcmH4VupQ/edit?usp=sharing

The layout for how the pages should look is found in this document. https://docs.google.com/document/d/1toG-WxUBr4qvCiQiX8Fi00Tf2QQnHVo_KEM3OlKeezs/edit?usp=sharing

**Comment by peterspdx** [comment]
@robmyers This is for you. Let's discuss during our legal/tech check in later today.

**Comment by robmyers** [comment]
I've added a "Publish" column with "Y" meaning the site generator should generate a page for the row in the spreadsheet - the export doesn't carry color information so I had to improvise.

**Comment by robmyers** [comment]
I changed the value to indicate that the page should be published to "Publish" for very hacky reasons.:-)

**Comment by robmyers** [comment]
@samanthalisae This is ready to evaluate - the German page is working well.

**Comment by robmyers** [comment]
Following our discussion in the meeting today I am marking this closed.

Thank you!
