### ISSUE TITLE
Database Disclaimer

### ISSUE THREAD

**Issue by samanthalisae** [creativecommons/caselaw#8]
Please put the following disclaimer on every individual page in the database (case law and scholarship pages).

Except where otherwise stated, please note that Creative Commons does not hold copyright in the court opinions and other judicial materials in this database or in the academic articles and other materials in this database.

**Comment by robmyers** [comment]
I have added this to the page footer for every page (under the license block at the bottom right).

This will show up when I next deploy the site at the end of the day today.

**Comment by peterspdx** [comment]
Thanks @robmyers 
@samanthalisae Can you please provide on private email an update on where you are with the issues we discussed when we last spoke, before our check in tomorrow 1:1? Would like to see all of those items closed out as discussed would be completed by Tuesday EOB.
