### ISSUE TITLE
empty tables

### ISSUE THREAD

**Issue by palak199** [creativecommons/caselaw#81]
## Description

Some of the tables do not have data, like the one in screenshot 

## Screenshots

![Screenshot from 2020-10-13 11-05-53](https://user-images.githubusercontent.com/43077980/95819864-8f6aa400-0d44-11eb-9b04-2d6b0655080e.png)

## Additional context

I think it will be better if the table headers appear only if there is content in that table, or maybe if the table is empty a row with -- can be used.
## Resolution

- [x] I would be interested in resolving this bug

**Comment by krysal** [comment]
Hi @palak199, thanks for your interest in the project, that is the old version of the site, we rebuild it with a new design, you can find the code in the [develop](https://github.com/creativecommons/caselaw/tree/develop) branch for now and see the preview at https://cc-caselaw.herokuapp.com/, the launch is planned to be soon. If you find something else there, please let us know.

We are not making any more changes to the jekyll site so I will close this.

**Comment by palak199** [comment]
Okay @krysal I guess I missed that, thankyou
