### ISSUE TITLE
filter by topics- on cases

### ISSUE THREAD

**Issue by palak199** [creativecommons/caselaw#82]
## Description

whenever I select one topic and then another, the results of the second topic get appended to first

## Expectation

I think it can be confusing for the user, so it is expected either the resultant rows are intersection of topics, or the previous topics get unselected when a new topic is clicked upon (even if the user forgets to do so)
## Screenshots

on selecting first only
![Screenshot from 2020-10-14 16-47-25](https://user-images.githubusercontent.com/43077980/95983199-da68e200-0e3e-11eb-88ff-dc4a7fb1391d.png)

on selecting second only
![Screenshot from 2020-10-14 16-47-17](https://user-images.githubusercontent.com/43077980/95983173-d0df7a00-0e3e-11eb-8c50-974b123ecc87.png)

screenshot when two topics are selected
![Screenshot from 2020-10-14 16-47-12](https://user-images.githubusercontent.com/43077980/95983158-ccb35c80-0e3e-11eb-84b6-3ddb5d842ce8.png)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by krysal** [comment]
It's made on purpose since there are few resources available at the moment, changing the filter to the intersection of topics will result in many empty tables.

This may change in the future though. I'll wait to know the opinion of @kgodey & @TimidRobot.

**Comment by palak199** [comment]
@krysal sure! but till it gets changed, can't we make the previous results disappear once a new selection is made?

**Comment by kgodey** [comment]
I think it's better to have the functionality as-is, if people want to select only a single topic, then they can unselect the previous topic manually. This gives them more filtering options by allowing them to find cases that match one of several topics.
