### ISSUE TITLE
Case Law and Scholarship

### ISSUE THREAD

**Issue by samanthalisae** [creativecommons/caselaw#9]
There are more cases and scholarship that have been turned green and are ready for uploading. 

The double unknown issue and the hyperlink issue has been fixed. 

https://docs.google.com/spreadsheets/d/1LVc6FM3RwJqqcyF6i3J1YDMfhzNaxbUgZ3YcmH4VupQ/edit?usp=sharing

**Comment by robmyers** [comment]
Thank you!

These have now been deployed.
